# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CryptoTax' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CryptoTax
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'lottie-ios','~> 2.5.0'
  pod 'Alamofire', '~> 5.4'
  pod 'Locksmith'
  pod 'CryptoSwift', '~> 1.4.1'

  pod 'Charts', '3.5.0'
  pod 'TinyConstraints' 
  pod 'AnyFormatKit'
end


